name: Build and Push Multi-Platform Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image tag version (e.g., 1.0.0, latest)'
        required: true
        default: 'latest'
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docker_build:
    name: Build and push multi-platform Docker image
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine version tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_type }}" = "tag" ]; then
            echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: |
            cyolosec/vanilla-guacamole:${{ steps.version.outputs.tag }}
            cyolosec/vanilla-guacamole:latest
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=cyolosec/vanilla-guacamole:buildcache
          cache-to: type=registry,ref=cyolosec/vanilla-guacamole:buildcache,mode=max

